version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - '8080:80'
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
