version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app # Mount the backend source code
      - /app/node_modules # Prevent overwriting node_modules
    command: npm run start:dev # Use nodemon for hot-reloading
